runtests.c: Fix compilation for undefined XML_CONTEXT_BYTES
Regression from 70d19d635a355da5b2cecf02ff6c01b3f56106ff

Compile error was:
  runtests.c: In function ‘byte_character_handler’:
  runtests.c:4195:11: error: ‘s’ undeclared (first use in this function)
       (void)s;